name: Compatibility Check
on:
  workflow_dispatch:
    inputs:
      baseBranch:
        # Why not using "--ref" property in workflow? It's because the option
        # uses workflow file in the ref, not the main branch. Declaring our own
        # baseBranch variable allows us to use the workflow definition in the
        # main branch against old branches. This does not require copying this
        # workflow file to the branch.
        description: 'Base branch'
        required: true
        type: string
      dependencyMavenCoordinates:
        description: 'The Maven coordinates of the dependency to check'
        required: true
        type: string
      preinstallRepositoryUrl:
        description: 'The URL of the repository to install into local Maven repository before running the check'
        required: false
        type: string
      preinstallRepositoryRef:
        description: 'The ref of the repository to install before running the check'
        required: false
        type: string
jobs:
  compatibility-check:
    runs-on: ubuntu-latest
    steps:
    - name: Print the input variables
      run: |
        echo "dependencyMavenCoordinates: ${{ github.event.inputs.dependencyMavenCoordinates }}"
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.inputs.baseBranch }}
    - name: Preinstall another repository if specified
      if: ${{ github.event.inputs.preinstallRepositoryUrl && github.event.inputs.preinstallRepositoryRef }}
      uses: actions/checkout@v2
      with:
        repository: ${{ github.event.inputs.preinstallRepositoryUrl }}
        ref: ${{ github.event.inputs.preinstallRepositoryRef }}
        path: preinstall-module
    - name: Install the artifacts of the module if specified
      if: ${{ github.event.inputs.preinstallRepositoryUrl && github.event.inputs.preinstallRepositoryRef }}
      run: |
        echo "pwd:"
        pwd
        echo
        echo "ls -alt:"
        ls -alt
        echo
        # Installs the artfacts to the local Maven repository
        .kokoro/build.sh
      shell: bash
      working-directory: preinstall-module
    - name: Show git commit log of the specified branch
      run: git log -1
    - uses: stCarolas/setup-maven@v4
      with:
        maven-version: 3.8.1
    - uses: actions/setup-java@v1
      with:
        java-version: 8
    - run: java -version
    - uses: GoogleCloudPlatform/cloud-opensource-java/dependency-update@github_action_dependency_updator
      with:
        mavenCoordinates: ${{ github.event.inputs.dependencyMavenCoordinates }}
    - name: Showing code diff after version update
      run: |
        git diff
      shell: bash
    - run: .kokoro/build.sh
      env:
        JOB_TYPE: test